name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-snap:
    name: Build and Deploy Snap
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/snap
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.6.0'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Snap
        run: yarn build

      - name: Upload Snap Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snap-build
          path: packages/snap/dist/
          retention-days: 1

  deploy-site:
    name: Deploy Site to Vercel
    runs-on: ubuntu-latest
    needs: deploy-snap
    defaults:
      run:
        working-directory: packages/site
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.6.0'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Download Snap Artifacts
        uses: actions/download-artifact@v3
        with:
          name: snap-build
          path: packages/snap/dist/

      - name: Build Site
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: packages/site
          vercel-args: '--prod'
